backbone: resnet18

# Feature Volume Channels
feature_volume_channels: 64

# Set the Anchor Steps
anchor_discretization:
  y: 72
  x: 128

# Image Dimensions
image_size:
  width: 640
  height: 360

# Dataset Image Dimensions
dataset_image_size:
  width: 1280
  height: 720

# Angles for the Anchor Proposals (Sames as used in LineCNN)
anchor_angles:
  left: [72., 60., 49., 39., 30., 22.]
  right: [108., 120., 131., 141., 150., 158.]
  bottom: [165., 150., 141., 131., 120., 108., 100., 90., 80., 72., 60., 49., 39., 30., 15.]

# Optimizer for training
optimizer:
  name: Adam
  parameters:
    lr: 0.0001
    weight_decay: 0.0001

# Scheduler for training
lr_scheduler:
  name: CosineAnnealingLR
  parameters:
    T_max: 166650

# Epochs
epochs: 300

# Batch Size
batch_size: 8

# Model Checkpoint Path
checkpoints_dir: "checkpoints"

# Model Checkpoint Interval (in epochs)
model_checkpoint_interval: 5

# Logs Path
logs_dir: "logs"

# Dataset settings
dataset:
  train:
    split: train
    root: "dataset_generator/greenhouse_train/"

  val:
    split: val
    root: "dataset_generator/greenhouse_val/"

  test:
    split: test
    root: "dataset_generator/greenhouse_test/"